export const ADD_TO_CART = "ADD_TO_CART";
export const SELECTED_TOUR = "SELECTED_TOUR";
export const REMOVE_SELECTED_TOUR = "REMOVE_SELECTED_TOUR";
export const CLEAR_CART = "CLEAR_CART";
export const SET_TOURS_TO_STORE = "SET_TOURS_TO_STORE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
