export const ADD_TOURS = "ADD_TOURS";
export const SELECTED_TOUR = "SELECTED_TOUR";
export const REMOVE_SELECTED_TOUR = "REMOVE_SELECTED_TOUR";
export const CLEAR_CART = "CLEAR_CART";
export const SET_TOURS_TO_STORE = "SET_TOURS_TO_STORE";
